ip: "192.168.0.3"
username: "pi"

trakt_id: "412681ab85026009c32dc6e525ba6226ff063aad0c1a374def0c8ee171cf121f"
trakt_secret: "714f0cb219791a0ecffec788fd7818c601397b95b2b3e8f486691366954902fb"
tmdb_key: "d3350c6d641ee4f16f94a6c0b3b809d1"

host: "{{ host }}@{{ ip }}"

dest_dir: "/home/pi/mc"
app_dir: "{{ dest_dir }}/app"
db_dir: "{{ dest_dir }}/mc-db"
cache_dir: "{{ dest_dir }}/mc-cache"
data_dir: "{{ dest_dir }}/media"

start_script: "start-docker-compose-production.sh"

error_board_url: "http://{{ ip }}:5000/api/v1"

backup_script: "backup.sh"
