version: '2'
services:
  minidlna:
    image: busybox:glibc
    restart: "no"
  transmission:
    image: busybox:glibc
    restart: "no"
  error-board:
    build:
      context: .
      dockerfile: ./docker/rpi-error-board-dev/Dockerfile
    restart: "no"
  app:
    build:
      context: .
      dockerfile: ./docker/rpi-media-center-dev/Dockerfile
    restart: "no"
    ports:
      - "3000:3000"
      - "3001:3001"
      - "8080:8080"
    links: []
    environment:
      - NODE_ENV=${NODE_ENV}
      - MC_X11_SUPPORT=
      - MEDIA_PATH=/data
      - DATA_PATH=/db
      - TRAVIS
      - TRAKT_TOKEN
      - TORRENT_PORT=3001
    volumes:
      - ${PWD}:/app
    devices:
      - "/dev/null:/dev/vchiq"
      - "/dev/null:/dev/fb0"
