language: node_js
node_js:
  - '6'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
  - npm install -g yarn
  - yarn install
script: npm run lint && npm run test:cov && npm run build:demo
after_success:
  - 'npm i coveralls'
  - 'cat coverage/lcov.info | ./node_modules/.bin/coveralls'
deploy:
  skip_cleanup: true
  provider: script
  script: demo/deploy.sh
  on:
    branch: master
